image: "python:3.9"

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - lint
  - build

pylint:
  stage: lint
  script:
    - pylint src --errors-only

docker_build:
  stage: build
  script:
    - docker build -t weather .
    - docker run weather