image: "python:3.9"



stages:
  - lint
  - build

pylint:
  stage: lint
  script:
    - pip install -r requirements.txt
    - pylint src --errors-only

docker_build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2 # not sure if this is needed
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker build -t weather .
    - docker run weather
